In [ ]:
import numpy as np
from numpy import *

In [ ]:
# creating only zeros as random element
a = zeros([2,3], int)
a

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
# arange
q = arange(100,50,-5)
print(q)

[100  95  90  85  80  75  70  65  60  55]


In [ ]:
# creating ones as random
b = ones([3,3], int)
b

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
# Mathematical operation
x = array([23,45,67,23,56,86])
print(sqrt(x))
print(max(x))
print(sort(x))
print(mean(a))

[4.79583152 6.70820393 8.18535277 4.79583152 7.48331477 9.2736185 ]
86
[23 23 45 56 67 86]
0.0


In [ ]:
# logspace (but in log table it takes)
s = logspace(1,4,5)
print(s)

[   10.            56.23413252   316.22776602  1778.27941004
 10000.        ]


In [ ]:
# linespace
p = linspace(20,30)   # max 50 number generate randomely
print(p)
p1 = linspace(20,30,15)
print(p1)


[20.         20.20408163 20.40816327 20.6122449  20.81632653 21.02040816
 21.2244898  21.42857143 21.63265306 21.83673469 22.04081633 22.24489796
 22.44897959 22.65306122 22.85714286 23.06122449 23.26530612 23.46938776
 23.67346939 23.87755102 24.08163265 24.28571429 24.48979592 24.69387755
 24.89795918 25.10204082 25.30612245 25.51020408 25.71428571 25.91836735
 26.12244898 26.32653061 26.53061224 26.73469388 26.93877551 27.14285714
 27.34693878 27.55102041 27.75510204 27.95918367 28.16326531 28.36734694
 28.57142857 28.7755102  28.97959184 29.18367347 29.3877551  29.59183673
 29.79591837 30.        ]
[20.         20.71428571 21.42857143 22.14285714 22.85714286 23.57142857
 24.28571429 25.         25.71428571 26.42857143 27.14285714 27.85714286
 28.57142857 29.28571429 30.        ]


In [ ]:
# reshape
c = array([[2,3,5],[4,6,7]])
d = c.reshape(3,2)
d

array([[2, 3],
       [5, 4],
       [6, 7]])

In [ ]:
c = arange(-5,5,3)
d = c.reshape(2,2)
d
print("Elements:",d)
print("Average of elements:",average(d))
print("Count of elements:",size(d))
print("Below elements which are below zer0:", d[d<0])


Elements: [[-5 -2]
 [ 1  4]]
Average of elements: -0.5
Count of elements: 4
Below elements which are below zer0: [-5 -2]
