In [ ]:
# Numpy--numerical python

In [ ]:
import numpy as np

In [ ]:
# creating an array

In [ ]:
# one dimensional array
a = np.array([3,4,5])
print("1D array:",a)
print("shape of 1D array:", a.shape)
print("No_of dimension of 1D array:", a.ndim)

1D array: [3 4 5]
shape of 1D array: (3,)
No_of dimension of 1D array: 1


In [ ]:
# two dimensional array
b = np.array([[2,3],[4,5]])
print("2D array:",b)
print("shape of 2D array:", b.shape)
print("No_of dimension of 2D array:", b.ndim)

2D array: [[2 3]
 [4 5]]
shape of 2D array: (2, 2)
No_of dimension of 2D array: 2


In [ ]:
# Three dimensional array
c = np.array([[[2,3],[4,5]],
              [[6,7],[8,9]]])
print("3D array:",c)
print("shape of 3D array:", c.shape)
print("No_of dimension of 3D array:", c.ndim)

3D array: [[[2 3]
  [4 5]]

 [[6 7]
  [8 9]]]
shape of 3D array: (2, 2, 2)
No_of dimension of 3D array: 3


In [ ]:
sales_data = np.array(
   [ [12,34,65,87],
    [45,76,11,78],
    [12,98,20,45],
    [33,61,33,12],
    [56,63,98,12],
    [10,20,30,40],
    [50,60,70,80] ])

In [ ]:
# Indexing the row
sales_data[4]

array([56, 63, 98, 12])

In [ ]:
# Indexing the specific element using indexing
sales_data[3][2]

np.int64(33)

In [ ]:
# Slicing
sales_data[:1]

array([[12, 34, 65, 87]])

In [ ]:
# Slicing specific elements
sales_data[5:,1]

array([20, 60])

In [ ]:
# using some conditions
sales_data[sales_data > 50]

array([65, 87, 76, 78, 98, 61, 56, 63, 98, 60, 70, 80])

In [ ]:
# extracting
sales_data[5:,3:]

array([[40],
       [80]])

In [ ]:
# Broadcasting
a = np.array([4,4,4,4])
b = 4
print(a + b)

[8 8 8 8]


In [ ]:
c = np.array([[2,3],[4,5]])
d = np.array([[6,7],[8,9]])
print(c + d)

[[ 8 10]
 [12 14]]


In [ ]:
# use case taking one data and performing some operations
data = sales_data[2]
print(data)
discount = data * 0.9
print(discount)

[12 98 20 45]
[10.8 88.2 18.  40.5]


In [ ]:
# adding each data in an array
add_data = np.array([100,100,100,100])
final = sales_data + add_data
print(final)

[[112 134 165 187]
 [145 176 111 178]
 [112 198 120 145]
 [133 161 133 112]
 [156 163 198 112]
 [110 120 130 140]
 [150 160 170 180]]
